// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugins} from '../models';
import {context} from '../models';
import {interop} from '../models';
import {http} from '../models';

export function RequestPlugins():Promise<Array<plugins.Info>>;

export function RequestSign(arg1:context.Context,arg2:interop.DataMessage):Promise<interop.DataMessage>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
