// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RequestPlugins() {
  return window['go']['plugins']['Manager']['RequestPlugins']();
}

export function RequestSign(arg1, arg2) {
  return window['go']['plugins']['Manager']['RequestSign'](arg1, arg2);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['plugins']['Manager']['ServeHTTP'](arg1, arg2);
}
